### ISSUE TITLE
Insecure `build-and-plugish.yarn`

### ISSUE THREAD

**Issue by bbortt** [mirioeggmann/cloudflare-ddns#1]
Your docker login might end up in a shell history and/or log files.. According to the official [documentation](https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin) you should provide the password via stdin.

```bash
$ echo ${DOCKER_LOGIN_PASSWORD} | docker login -u ${DOCKER_LOGIN_USERNAME} --password-stdin ${DOCKER_REPOSITORY}
```

**Comment by mirioeggmann** [comment]
Good point, thx!

Changed it to: `$ echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin`

**Comment by bbortt** [comment]
Nice one :) almost as good as the issue title^^
